# Generated by Django 4.2.8 on 2023-12-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='product-images/default.gif', help_text='Upload a product image', upload_to='product-images/', verbose_name='image'),
        ),
    ]
